on:
  push:
    branches:
      - master

jobs:
  
  deploy:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        run: |
          TARGET="/www/wwwroot/zakat.akademi.my.id/web-si-zakat-ci3"
          ssh -i "$PRIVATE_KEY" -T friczky@34.101.143.10 << EOF
          cd "$TARGET"
          git pull
          EOF
          
