on:
  push:
    branches:
      - master

jobs:
  
  deploy:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        run: 
          echo "this is private key $PRIVATE_KEY"
          
